{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "secret-manager.fullname" . }}-metrics
  labels:
    {{- include "secret-manager.labels" . | nindent 4 }}
  annotations:
    prometheus.io/path: "/metrics"
    prometheus.io/scrape: 'true'
    prometheus.io/port: "{{ .Values.prometheus.service.port }}"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: {{ .Values.prometheus.service.port }}
      protocol: TCP
  selector:
    {{- include "secret-manager.selectorLabels" . | nindent 4 }}
{{- end }}
