apiVersion: v2
name: secret-manager
description: External secret management for Kubernetes
type: application
version: 0.1.1
appVersion: 0.0.0
keywords:
  - kubernetes
  - secret
  - secretstore
  - secret-management
  - vault
  - aws
  - azure
  - crd
home: https://github.com/itscontained/secret-manager
sources:
  - https://hub.docker.com/r/itscontained/secret-manager
  - https://quay.io/repository/itscontained/secret-manager
  - https://github.com/orgs/itscontained/packages/container/secret-manager
maintainers:
  - name: DirtyCajunRice
    email: nick@cajun.pro
  - name: mcavoyk
    email: kellinmcavoy@gmail.com
annotations:
  artifacthub.io/operator: true
  artifacthub.io/links: |
    - name: Source Code
      url: https://github.com/itscontained/secret-manager
    - name: DockerHub Image
      url: https://hub.docker.com/r/itscontained/secret-manager
    - name: Quay.io Image
      url: https://quay.io/repository/itscontained/secret-manager
    - name: GHCR Image
      url: https://github.com/orgs/itscontained/packages/container/secret-manager
  artifacthub.io/maintainers: |
    - name: Nicholas St. Germain
      email: nick@cajun.pro
    - name: Kellin McAvoy
      email: kellinmcavoy@gmail.com