name: Release Charts

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout secret-manger
        uses: actions/checkout@v2
        with:
          path: secret-manager
      - name: Import Secrets
        uses: RichiCoder1/vault-action@v1.0.1
        with:
          url: ${{ secrets.VaultURL }}
          method: approle
          roleId: ${{ secrets.appRoleID }}
          secretId: ${{ secrets.appSecretID }}
          path: kv-v2
          secrets: |
            auth/dockerhubci username | DOCKERHUB_USERNAME ;
            auth/dockerhubci token | DOCKERHUB_TOKEN;
            auth/github token | GITHUB_PAT;
      - name: Checkout Chart Repo
        uses: actions/checkout@v2
        with:
          token: "${{ env.GITHUB_PAT }}"
          repository: "itscontained/charts"
          ref: master
          path: charts
      - name: Configure Git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        run: |
          curl -fsSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      - name: Instasll chart-releaser
        run: |
          wget https://github.com/helm/chart-releaser/releases/download/v1.0.0/chart-releaser_1.0.0_linux_amd64.tar.gz
          tar xzvf chart-releaser_1.0.0_linux_amd64.tar.gz cr
      - name: Release Chart
        run: |
          helm package secret-manager/deploy/charts/secret-manager/ --destination ${CR_PACKAGE_PATH} --dependency-update
          CR_TOKEN=${GITHUB_PAT}
          ./cr upload && ./cr index
          cd charts/ && git add . && git commit -m "release chart" && git push
        env:
          CR_CHARTS_REPO: "https://charts.itscontained.io"
          CR_INDEX_PATH: "charts/index.yaml"
          CR_OWNER: "itscontained"
          CR_GIT_REPO: "charts"
          CR_PACKAGE_PATH: "charts/packages/"