name: Release Container
on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  push:
    branches: master
    tags:
      - 'v*.*.*'
  pull_request:
    branches: master
    paths:
      - 'cmd/**'
      - 'pkg/**'
      - 'go.mod'
      - 'go.sum'
env:
  IMAGES: ${{ github.repository_owner }}/secret-manager
  PLATFORMS: "linux/amd64,linux/arm64,linux/arm/v7"
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: '~1.15.0'
      - name: Setup Kubebuilder
        uses: ./.github/actions/setup-kubebuilder-action
      - name: Lint
        run: |
          make lint-install
          make lint
      - name: Test
        run: make test
  docker:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=itscontained/secret-manager
          VERSION=edge
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/v}
          fi
          if [ "${{ github.event_name }}" = "schedule" ]; then
            VERSION=nightly
          fi
          TAGS="${VERSION}"
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS,latest"
          fi
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=build_date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
          echo ::set-output name=vcs_ref::${GITHUB_SHA::8}
      - uses: ./.github/actions/docker-target-image-list-action
        name: Generate Target Images
        id: gen-tags
        with:
          images: ${{ env.IMAGES }}
          tags: ${{ steps.prep.outputs.tags }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          version: latest
          driver-opts: image=moby/buildkit:master
      - name: Docker Multi Login
        uses: ./.github/actions/docker-multi-login-action
        env:
          secrets: ${{ toJSON(secrets) }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ env.PLATFORMS }}
          pull: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.gen-tags.outputs.fully-qualified-target-images }}
          build-args: |
            VERSION=${{ steps.prep.outputs.version }}
            BUILD_DATE=${{ steps.prep.outputs.build_date }}
            VCS_REF=${{ steps.prep.outputs.vcs_ref }}
      - name: Inspect
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          IFS=',' read -r -a images <<< "${{ steps.gen-tags.outputs.fully-qualified-target-images }}"
          for image in "${images[@]}"; do
              docker buildx imagetools inspect ${image}
          done
