name: e2e
on:
  push:
    branches:
    - '*'
    tags:
      - 'v*.*.*'
    paths:
      - 'cmd/**'
      - 'pkg/**'
      - 'e2e/**'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'
  pull_request:
    branches:
      - '*'
    tags:
    paths:
      - 'cmd/**'
      - 'pkg/**'
      - 'e2e/**'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'
jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout secret-manger
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        with:
          version: v0.9.0
          node_image: kindest/node:v1.19.1
          cluster_name: secret-manager
      - name: Run e2e tests
        timeout-minutes: 30
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get github.com/onsi/ginkgo/ginkgo
          make e2e-test
