name: Release Chart

on:
  push:
    tags:
      - '*'
  pull_request:
    branches: master
    paths:
      - 'deploy/charts/**'
    paths-ignore:
      - 'deploy/charts/secret-manager/README.md'
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout secret-manger
        uses: actions/checkout@v2
      - name: Fetch history
        run: |
          git fetch --prune --unshallow;
          echo ::set-env name=commitmsg::$(git log --format=%B -n 1 ${{ github.event.after }})
      - name: lint
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        if: "! contains(env.commitmsg, '[skip chart-lint]')"
        with:
          command: lint
          config: deploy/charts/ct.yaml
      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        if: "steps.lint.outputs.changed == 'true' && ! contains(env.commitmsg, '[skip chart-install]')"
      - name: test
        uses: helm/chart-testing-action@v1.0.0
        if: "steps.lint.outputs.changed == 'true' && ! contains(env.commitmsg, '[skip chart-install]')"
        with:
          command: install
          config: deploy/charts/ct.yaml
  release:
    runs-on: ubuntu-latest
    needs: lint-and-test
    if: "github.event_name != 'pull_request'"
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "${{ env.GHCR_USERNAME }}"
          git config --global user.email "${{ env.GHCR_USERNAME }}@users.noreply.github.com"
      - name: Checkout secret-manger
        uses: actions/checkout@v2
        with:
          path: secret-manager
      - name: Checkout Chart Repo
        uses: actions/checkout@v2
        with:
          token: ${{ env.GHCR_PASSWORD }}
          repository: "itscontained/charts"
          ref: gh-pages
          path: charts
      - name: Install Helm
        run: |
          curl -fsSLo get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
      - name: Install chart-releaser
        run: |
          wget https://github.com/helm/chart-releaser/releases/download/v1.0.0/chart-releaser_1.0.0_linux_amd64.tar.gz
          tar xzvf chart-releaser_1.0.0_linux_amd64.tar.gz cr
      - name: Copy CRDs to chart
        run: make crds-to-chart
      - name: Release Chart
        run: |
          sed -i 's/%%APPVERSION%%/${GITHUB_REF#refs/tags/v}/' deploy/charts/secret-manager/Chart.yaml
          helm package secret-manager/deploy/charts/secret-manager/ --destination .cr-release-packages
          ./cr upload -t ${GITHUB_PAT} && ./cr index
          cd charts/ && git add . && git commit -m "release chart" && git push
        env:
          CR_CHARTS_REPO: "https://charts.itscontained.io"
          CR_INDEX_PATH: "charts/index.yaml"
          CR_OWNER: "itscontained"
          CR_GIT_REPO: "charts"